export const stopWords = new Set([
  "the",
  "and",
  "you",
  "to",
  "i",
  "a",
  "it",
  "in",
  "of",
  "my",
  "is",
  "that",
  "for",
  "me",
  "on",
  "with",
  "t",
  "s",
  "your",
  "be",
  "all",
  "have",
  "but",
  "so",
  "not",
  "as",
  "was",
  "we",
  "this",
  "there",
  "are",
  "they",
  "she",
  "who",
  "don",
  "her",
  "when",
  "now",
  "can",
  "from",
  "what",
  "his",
  "just",
  "where",
  "one",
  "out",
  "up",
  "had",
  "has",
  "will",
  "no",
  "if",
  "do",
  "at",
  "him",
  "by",
  "would",
  "could",
  "their",
  "them",
  "how",
  "an",
  "or",
  "some",
  "were",
  "then",
  "been",
  "here",
  "back",
  "down",
  "said",
  "say",
  "let",
  "than",
  "into",
  "very",
  "only",
  "more",
  "even",
  "through",
  "got",
  "take",
  "did",
  "need",
  "see",
  "come",
  "want",
  "always",
  "again",
  "long",
  "little",
  "too",
  "well",
  "know",
  "never",
  "much",
  "before",
  "should",
  "must",
  "these",
  "those",
  "every",
  "aren",
  "ain",
  "won",
  "yet",
  "ever",
  "once",
  "why",
  "after",
  "yes",
  "came",
  "took",
  "get",
  "make",
  "turned",
  "happens",
  "happened",
  "going",
  "away",
  "give",
  "about",
  "other",
  "may",
  "might",
  "without",
  "upon",
  "shall",
  "tell",
  "show",
  "like",
  "keep",
  "look",
  "left",
  "around",
  "another",
  "nothing",
  "something",
  "many",
  "everybody",
  "everyone",
  "between",
  "kind",
  "ask",
  "hear",
  "though",
  "better",
  "live",
  "actually",
  "didn",
])

// Butterfly diagram data from диаграмма-бабочка-3GCX4.py
// Early period (1967-1974): Bodily images / Телесные образы
export const earlyPeriodWords = [
  { word: "LOVER", count: 92 },
  { word: "MAN", count: 30 },
  { word: "WAR", count: 24 },
  { word: "LADY", count: 18 },
  { word: "BODY", count: 17 },
  { word: "HAND", count: 16 },
  { word: "WOMAN", count: 15 },
  { word: "GREEN", count: 12 },
]

// Late period (2000-2016): Philosophical meanings / Философские смыслы
export const latePeriodWords = [
  { word: "HEART", count: 36 },
  { word: "PLACE", count: 26 },
  { word: "DAY", count: 23 },
  { word: "LIGHT", count: 22 },
  { word: "TRUTH", count: 21 },
  { word: "HOME", count: 19 },
  { word: "MIND", count: 17 },
  { word: "HEALING", count: 14 },
]

// Word cloud data based on corpus frequency analysis
// Sizes calculated from occurrence counts
export const realWordCloudData = [
  // High frequency (primary)
  { word: "love", count: 312, size: 48 },
  { word: "night", count: 187, size: 42 },
  { word: "time", count: 156, size: 38 },
  { word: "heart", count: 143, size: 36 },
  { word: "eyes", count: 128, size: 34 },
  { word: "light", count: 119, size: 32 },

  // Medium-high frequency (accent)
  { word: "dance", count: 98, size: 28 },
  { word: "song", count: 94, size: 27 },
  { word: "lover", count: 92, size: 27 },
  { word: "woman", count: 87, size: 26 },
  { word: "soul", count: 82, size: 25 },
  { word: "fire", count: 78, size: 24 },
  { word: "dark", count: 74, size: 23 },
  { word: "rain", count: 71, size: 22 },
  { word: "world", count: 68, size: 22 },

  // Medium frequency
  { word: "broken", count: 62, size: 20 },
  { word: "tower", count: 58, size: 19 },
  { word: "freedom", count: 54, size: 18 },
  { word: "prayer", count: 51, size: 18 },
  { word: "beauty", count: 48, size: 17 },
  { word: "mercy", count: 45, size: 16 },
  { word: "golden", count: 42, size: 16 },
  { word: "silence", count: 39, size: 15 },
  { word: "holy", count: 36, size: 15 },
  { word: "truth", count: 34, size: 14 },

  // Lower frequency (supporting)
  { word: "hallelujah", count: 31, size: 14 },
  { word: "war", count: 28, size: 13 },
  { word: "flesh", count: 26, size: 13 },
  { word: "longing", count: 24, size: 12 },
  { word: "stranger", count: 22, size: 12 },
  { word: "faith", count: 20, size: 11 },
  { word: "demon", count: 18, size: 11 },
  { word: "angel", count: 17, size: 10 },
  { word: "wound", count: 15, size: 10 },
  { word: "prophet", count: 14, size: 10 },
]

// Corpus structure from cohen_clean_corpus.json
export interface CorpusSong {
  title: string
  album: string
  year: number | string
  url: string
}

// Album metadata derived from corpus analysis
export const albumsFromCorpus = [
  { title: "Songs of Leonard Cohen", year: 1967, period: "early" },
  { title: "Songs from a Room", year: 1969, period: "early" },
  { title: "Songs of Love and Hate", year: 1971, period: "early" },
  { title: "New Skin for the Old Ceremony", year: 1974, period: "early" },
  { title: "Death of a Ladies' Man", year: 1977, period: "middle" },
  { title: "Recent Songs", year: 1979, period: "middle" },
  { title: "Various Positions", year: 1984, period: "middle" },
  { title: "I'm Your Man", year: 1988, period: "middle" },
  { title: "The Future", year: 1992, period: "middle" },
  { title: "Ten New Songs", year: 2001, period: "late" },
  { title: "Dear Heather", year: 2004, period: "late" },
  { title: "Old Ideas", year: 2012, period: "late" },
  { title: "Popular Problems", year: 2014, period: "late" },
  { title: "You Want It Darker", year: 2016, period: "late" },
  { title: "Thanks for the Dance", year: 2019, period: "posthumous" },
]

// Comparison data: early (1967-1974) vs late (2000-2016) periods
export const periodComparisonData = {
  early: {
    label: "Ранний период (1967–1974)",
    description: "Мир плоти и образов",
    color: "#2ecc71", // seagreen
    topWords: earlyPeriodWords,
    characteristics: ["Physical imagery", "Romantic love", "War & conflict", "Feminine archetypes", "Sensual language"],
  },
  late: {
    label: "Поздний период (2000–2019)",
    description: "Мир духовности и итогов",
    color: "#f1c40f", // goldenrod
    topWords: latePeriodWords,
    characteristics: [
      "Abstract concepts",
      "Spiritual themes",
      "Light & darkness",
      "Inner journey",
      "Philosophical reflection",
    ],
  },
}
